### ISSUE TITLE
Small bug.

### ISSUE THREAD

**Issue by alex-ozdemir** [benjaminkiesl/drat2er#4] opened 2019-01-22 11:27 UTC
There seems to be a small bug in `drat-trim` which is causing `drat2er` to misbehave. In particular, on my machine `drat2er` fails to correctly convert the proof

```
0
```

for formula

```
p cnf 2 3
1 0
-2 0
2 0
```

. Instead it produces a blank proof.

The core reasons seems to be that `drat-trim` never actually closes the LRAT file after conversion ([this](https://github.com/benjaminkiesl/drat2er/blob/master/third-party/drat-trim/drat-trim.c#L508) line never runs), so the (short) LRAT file doesn't get flushed until `drat2er` exits, so `drat2er`'s conversion machinery doesn't reach any LRAT proof at all.

I could imagine a few fixes, but the simplest is probably to put a failsafe file close into `drat-trim`.

I'm happy to help in anyway I can!

**Comment by benjaminkiesl** [comment] 2019-01-22 13:11
Hi Alex,

Thanks for your detailed bug report! Your diagnosis was right: The bug was indeed caused by drat-trim, which - as you observed - didn't close its LRAT file when detecting a conflict caused by two complementary unit clauses. I now fixed the bug within the drat-trim code in this drat2er repository but I also informed Marijn Heule about the bug so he can change the original code in the drat-trim repository. Please let me know in case there is still an issue on your machine!

Cheers,
Benjamin

**Comment by alex-ozdemir** [comment] 2019-01-22 17:32
Ah -- nice job identifying the situation in which this arises. Thanks for the rapid response!

**Closed as completed** 2019-01-23 05:31 UTC
